---
volumes:
  slsk-data:
    labels:
      net.mafro.kopia: true

networks:
  caddy:
    external: true

services:
  slskd:
    image: slskd/slskd:${SLSKD_VERSION:-latest}
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Australia/Melbourne
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/download
      - SLSKD_INCOMPLETE_DIR=/app/incomplete
      - SLSKD_CONFIG=/slskd.yml
      - SLSKD_DEBUG=false
    networks:
      - caddy
      - default
    volumes:
      - slsk-data:/app
      - ./slskd.yml:/slskd.yml:ro
      - /home/mafro/music:/music:ro
      - /home/mafro/music/unsorted:/download
    env_file:
      - .secrets
    labels:
      caddy: slsk.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 5030}}"
